import type { Metadata } from "next";
import {  Nunito } from "next/font/google";  // Import Nunito as well
import "./globals.css";


// Initialize both fonts
const nunito = Nunito({ subsets: ["latin"], weight: ["200", "400", "700", "900"] }); // Specify weights

export const metadata: Metadata = {
  title: "Bhakti Baba",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        {children}
      </body>
    </html>
  );
}
